name: 🚀 Full Release Pipeline

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Build, Test, and Release
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4️⃣ Train or update model
      - name: Train or update model
        run: |
          version="${GITHUB_REF_NAME}"
          python model/train.py --version $version

      # 5️⃣ Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 6️⃣ Log in to GitHub Container Registry
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 7️⃣ Build Docker image
      - name: Build Docker image
        env:
          IMAGE: ghcr.io/${{ github.repository }}:${{ github.ref_name }}
        run: |
          docker build -t $IMAGE --build-arg VERSION=${{ github.ref_name }} .

      # 8️⃣ Smoke test Docker container
      - name: Smoke test container
        env:
          IMAGE: ghcr.io/${{ github.repository }}:${{ github.ref_name }}
        run: |
          docker run -d -p 8000:8000 --name app $IMAGE
          sleep 5
          curl -f http://localhost:8000/health
          docker stop app && docker rm app

      # 9️⃣ Push Docker image to GHCR
      - name: Push Docker image
        env:
          IMAGE: ghcr.io/${{ github.repository }}:${{ github.ref_name }}
        run: docker push $IMAGE

      # 🔟 Extract metrics (if generated by training)
      - name: Extract model metrics
        run: |
          mkdir -p out
          if [ -f "model/metrics.json" ]; then
            cp model/metrics.json out/metrics.json
          elif [ -f "metrics.json" ]; then
            mv metrics.json out/metrics.json
          else
            echo '{}' > out/metrics.json
          fi

      # 1️⃣1️⃣ Create GitHub Release and upload assets
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          name: "Release ${{ github.ref_name }}"
          body: |
            🧠 **Automatic Release for** `${{ github.ref_name }}`

            ✅ Model retrained and validated  
            ✅ Docker image built and pushed to GHCR  
            ✅ Container smoke test passed  
            ✅ Metrics + model uploaded as release assets  

            See [CHANGELOG.md](./CHANGELOG.md) for more details.
          files: |
            model/model.joblib
            out/metrics.json
            CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}